version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx_webserver
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - 3306:3306
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: ["composer"]

  npm:
    image: node:16
    container_name: npm
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: ["npm"]

networks:
  laravel:

volumes:
  db_data: